<?php
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT

unset($CFG);
global $CFG;
$CFG = new stdClass();

// ========== DB connection string info ==========
// Choose one database driver
// Uncomment based on your database type

// MySQL/MariaDB
$CFG->dbtype    = getenv('DB_TYPE') ?: 'mysqli';
$CFG->dblibrary = 'native';
$CFG->dbhost    = getenv('DB_HOST') ?: 'localhost';
$CFG->dbname    = getenv('DB_NAME') ?: 'moodle';
$CFG->dbuser    = getenv('DB_USER') ?: 'moodle';
$CFG->dbpass    = getenv('DB_PASSWORD') ?: '';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'bigblobs' => true,
  'debugdb' => false,
  'debugdbresult' => false,
);

// ========== WEB SETTINGS ==========
$CFG->wwwroot   = getenv('MOODLE_URL') ?: 'http://localhost';
$CFG->slasharguments = true;
$CFG->admin = 'admin';

// ========== DATA DIRECTORY LOCATION ==========
$CFG->dataroot  = '/var/moodledata';
$CFG->directorypermissions = 0777;

// ========== DIRECTORY STRUCTURE ==========
$CFG->tempdir = $CFG->dataroot.'/temp';
$CFG->cachedir = $CFG->dataroot.'/cache';
$CFG->localcachedir = $CFG->dataroot.'/localcache';

// ========== SESSION HANDLING ==========
$CFG->sessionhandler = 'database';
ini_set('session.name', 'MoodleSessionID');
ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_secure', 1);
ini_set('session.cookie_samesite', 'Lax');

// ========== SECURITY SETTINGS ==========
$CFG->passwordpolicy = true;
$CFG->minpasswordlength = 8;
$CFG->minpassworddigits = 1;
$CFG->minpasswordlower = 1;
$CFG->minpasswordupper = 1;
$CFG->minpasswordnonalphanum = 1;

$CFG->forcelogin = false;
$CFG->forceloginforprofiles = false;

// ========== PERFORMANCE SETTINGS ==========
$CFG->cachejs = true;
$CFG->cachetext = true;
$CFG->usesessions = true;

// Enable caching
$CFG->cachestore_file_path_cache = $CFG->cachedir;

// ========== EMAIL SETTINGS ==========
$CFG->smtphosts = getenv('SMTP_HOST') ?: 'localhost';
$CFG->smtpuser = getenv('SMTP_USER') ?: '';
$CFG->smtppass = getenv('SMTP_PASSWORD') ?: '';
$CFG->smtpmaxbulk = 400;
$CFG->noreplyaddress = getenv('SMTP_FROM') ?: 'noreply@example.com';
$CFG->sitemailcharset = 'UTF-8';

// ========== LANGUAGE & LOCALE ==========
$CFG->lang = getenv('MOODLE_LANG') ?: 'en';
$CFG->langotherroot = $CFG->dataroot.'/lang/';
$CFG->langmenu = true;

// ========== PLUGINS & THEMES ==========
$CFG->themedir = $CFG->dirroot.'/theme';
$CFG->plugindir = $CFG->dirroot.'/lib/plugins';
$CFG->rss_client_timeout = 6;

// ========== DEBUG SETTINGS ==========
// IMPORTANT: Disable debug in production!
define('DEBUG_DEVELOPER', 32767);
define('DEBUG_NORMAL', 6143);
define('DEBUG_MINIMAL', 6143);
define('DEBUG_NONE', 0);

$CFG->debug = DEBUG_NONE;  // Change to DEBUG_DEVELOPER for testing
$CFG->debugdisplay = false;
$CFG->perfdebug = 7;
$CFG->debugstringkeys = false;

// Log errors
$CFG->logdir = $CFG->dataroot.'/log';

// ========== CRON SETTINGS ==========
$CFG->cronremotepassword = 'changeme';  // Change this!
$CFG->cronclionly = true; // Cron via web disabled for security

// ========== FILE UPLOAD SETTINGS ==========
$CFG->maxbytes = 52428800; // 50MB
$CFG->userquota = 104857600; // 100MB per user
$CFG->filelifetime = 86400 * 30;

// ========== COURSE SETTINGS ==========
$CFG->coursesnumber = 10;
$CFG->frontpage = 1;
$CFG->frontpageloggedin = 1;
$CFG->numsections = 52;

// ========== AUTHENTICATION ==========
$CFG->authloginviaemail = false;
$CFG->allowaccountssonexternaldb = false;
$CFG->allowuseraccountsonexternaldb = false;

// ========== MAINTENANCE MODE ==========
// $CFG->maintenance_enabled = true;
// $CFG->maintenance_message = 'System is under maintenance. Please try again later.';

// ========== TRUSTED HOSTS ==========
$CFG->trustedcallers = array();

// ========== ADDITIONAL SECURITY ==========
$CFG->enablerssfeeds = false;
$CFG->enablebadges = false;
$CFG->enablecomments = true;

// ========== SYSTEM SETTINGS ==========
$CFG->timezone = 'UTC';
$CFG->sslproxy = false;
$CFG->proxyhost = '';
$CFG->proxyport = 0;
$CFG->proxytype = 'HTTP';
$CFG->proxybypass = '';
$CFG->proxyuser = '';
$CFG->proxypassword = '';

// ========== FILTER SETTINGS ==========
$CFG->textfilteringdefault = true;

// ========== BACKUP SETTINGS ==========
$CFG->backup_auto_weekday = 0;
$CFG->backup_auto_hour = 2;
$CFG->backup_auto_minute = 0;
$CFG->backup_auto_storage = 0; // 0 = course area, 1 = backup area
$CFG->backup_shortname = 1;
$CFG->backup_auto_skip_hidden = true;
$CFG->backup_auto_skip_moddata = false;

// ========== REQUIRE ALL CONFIG ==========
// IMPORTANT: Do not remove this line
require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace issues.
